### ISSUE TITLE
Train/Val split

### ISSUE THREAD

**Issue by versatran01** [castacks/tartanair_tools#12]
Is there a suggested train/val split for this dataset?

**Comment by Amigoshan** [comment]
Not really.

**Comment by versatran01** [comment]
Would you mind recommend one?

**Comment by Amigoshan** [comment]
Well, in my personal study, I separated the data from two environments soul-city and seaside-town for testing. I guess one recommendation would be to separate environments rather than randomly select trajectories from all environments. In the former case, it is stronger for testing the generalization ability.
