### ISSUE TITLE
semantic labels

### ISSUE THREAD

**Issue by alexandervakhitov** [castacks/tartanair_tools#14]
Hi! That is a really good dataset! I'd like to make the use of the semantic annotations available in it. Which set of semantic classes is used on the dataset? I haven't found any tools or documentation describing the class ids and labels... Could you please provide me with this information? Thank you!

**Comment by Amigoshan** [comment]
Hi, here is the information about the semantic labels: [https://github.com/castacks/tartanair_tools/blob/master/data_type.md#segmentation-image](https://github.com/castacks/tartanair_tools/blob/master/data_type.md#segmentation-image)
Basically, we are adopting what AirSim have: [https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#segmentation](https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#segmentation)

**Comment by ganlumomo** [comment]
Hi! @Amigoshan, I have read both links but still not clear about the semantic segmentation labels. Because according to [https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#segmentation](url), the labels provided depend on experimental setting (basically code) when you collect them. Could you give more information regarding this?


Specifically, I have the following questions:
1. I understand that the labels are from 0-255 from an object mesh, but how do I suppose to know the exact mesh name now?
2. Is an object for example "ground" has the same label in all the sequences? Because otherwise, the semantic segmentation labels are not very useful.

Thank you so much for your help!

**Comment by Qjizhi** [comment]
> Hi! @Amigoshan, I have read both links but still not clear about the semantic segmentation labels. Because according to [https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#segmentation](url), the labels provided depend on experimental setting (basically code) when you collect them. Could you give more information regarding this?
> 
> Specifically, I have the following questions:
> 
>     1. I understand that the labels are from 0-255 from an object mesh, but how do I suppose to know the exact mesh name now?
> 
>     2. Is an object for example "ground" has the same label in all the sequences? Because otherwise, the semantic segmentation labels are not very useful.
> 
> 
> Thank you so much for your help!

I have the same question.

**Comment by kwea123** [comment]
#22 same issue
so there is no `id -> name` mapping available. The id is the same within a scene, but not necessarily the same for another, e.g. the ground for scene A can be 22 but 99 for scene B
