### ISSUE TITLE
Transformation from NED to Cam

### ISSUE THREAD

**Issue by amin-abouee** [castacks/tartanair_tools#37]
Hi,
Tartain air is my training dataset for a deep learning odometry project.
In your dataset, the poses are in NED coordinate while I need to convert them to camera (opencv) coordinate system[right-down-forward]. For this purpose, you also implemented a function as [ned2cam](https://github.com/castacks/tartanair_tools/blob/b2f023bbca5606c05d4189811c3eee6f99564037/evaluation/trajectory_transform.py#L21) that converts a ned trajectory into my desired camera coordinate system.
So the question is, why do you need to apply the right multiplication `(.dot(T_inv))` for this transformation : `ttt=T.dot(tt).dot(T_inv)`.

When you have the pose of a frame with respect to a world pose in NED coordinate, you just need to apply the transformation from NED to Cam (T matrix in your formula) to have it in Cam coordinate! So then, what is the point of T_inv there?   
![Notepad5_1](https://user-images.githubusercontent.com/2705755/185005579-124339d3-45c1-4b9d-99ba-5c776f202bcb.png)

**Comment by ccj5351** [comment]
I think the code in [ned2cam](https://github.com/castacks/tartanair_tools/blob/b2f023bbca5606c05d4189811c3eee6f99564037/evaluation/trajectory_transform.py#L21) is correct. 

## In short: 

- OpenCV style camera-to-world pose is calculated as:

```
$T^{w}_{c}$ = $T^{w}_{wned}$ * $T^{wned}_{cned} $* $T^{cned}_{c}$ = T.dot(tt).dot(T_inv) (as what you mentioned in the function ned2cam)
note: $T^_{w}_{wned}$ in LaTex style.
```
Assume we have the following coordinate systems:

- `wned`: world coordinate in NED (x Forward, y Right, z Down) format;
- `cned`: camera coordinate in NED (x Forward, y Right, z Down) format;
- `w`: world coordinate in OpenCV style (x Right, y Down, z Forward);
- `c`: camera coordinate in OpenCV style (x Right, y Down, z Forward);

## Transformation from NED to OpenCV Style Coordinate System
### Why do we need OpenCV style camera pose? 

It is because we use the following pipeline to connect RGB, camera and world:

###  How to get the transformation matrix from NED to OpenCV Style
- The matrix is defined as $T^_{w}_{wned}$, to map the points $P^{wned}$ to the points $P^{w}$, i.e., 

$P^{w}$ = $T^_{w}_{wned}$ * $P^{wned}$

- To find $T^_{w}_{wned}$ is to project (or to calculate dot-product between) each axis of $x^{wned}$, $y^{wned}$, $z^{wned}$, into the axis $x^w$, $y^w$, $z^w$. This is how the variable [T](https://github.com/castacks/tartanair_tools/blob/b2f023bbca5606c05d4189811c3eee6f99564037/evaluation/trajectory_transform.py#L25) is obtained.
- Do not forget that the transformation from NED to OpenCV, have to be applied twice: one for `w` and `wned`, another for `c` and `cned`. This is why you see 'dot(T_inv)' in the code.

**Comment by amin-abouee** [comment]
Thanks for your answer
