### ISSUE TITLE
How to use data on azure?

### ISSUE THREAD

**Issue by ngthanhtin** [castacks/tartanair_tools#4]
Hi, I have used the sample notebook locally to access the data. But each time I accessed an image, the speed is very slow. So my question is that is it right when using the notebook locally or other ways? Thank you

**Comment by Amigoshan** [comment]
Hi, the notebook is not suggested to use locally, because as you described the speed is very slow. To use data on Azure, you can set up a virtual machine following Microsoft's guidelines https://azure.microsoft.com/en-us/services/virtual-machines/. One thing we should mention is our data account is located at "US East", so I suggest you create a machine in the same location. But I'm afraid it's not free. You can also download the zip files to your local machine as described here https://github.com/castacks/tartanair_tools#download-data-to-your-local-machine.

**Comment by ngthanhtin** [comment]
Thank you for your reply.
